// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package net.bigeon.mcdas.aggregator;

import java.time.LocalDateTime;

/************************************************************/
/** Interface of a data cache */
public interface Cache {
    /** Remove all data from the cache */
    void flush();

    /** Add a lock to keep new data if it is newer than the given date.
     *
     * @param from date to lock from */
    void lock(LocalDateTime from);

    /** Release a lock on the given date
     * 
     * @param lock the lock to release. */
    void release(LocalDateTime lock);
}
